Repository dizak/mothulity, pull requests merged in 2019-06, with the labels that each got.

#124 Enh#123
  .travis.yml
  test_data/analysis/mltp_smpl/results/files_list
  test_data/analysis/mltp_smpl/script/analysis_travis_job.sh
  test_data/analysis/mltp_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.0.03.cons.tax.summary
  test_data/analysis/mltp_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.0.030.cons.tax.summary
  test_data/analysis/mltp_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.shared
  test_data/analysis/single_smpl/results/files_list
  test_data/analysis/single_smpl/shared_tax/.analysis_travis_job.2018510105625
  test_data/analysis/single_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.0.03.cons.tax.summary
  test_data/analysis/single_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.shared
  test_data/config/mothulity.config
  test_data/database/t19.align
  test_data/database/t19.tax
  test_data/new_run/mltp_smpl/fastq/F3D0_S188_L001_R1_001.fastq
  test_data/new_run/mltp_smpl/fastq/F3D0_S188_L001_R2_001.fastq
  test_data/new_run/mltp_smpl/fastq/F3D2_S190_L001_R1_001.fastq
  test_data/new_run/mltp_smpl/fastq/F3D2_S190_L001_R2_001.fastq
  test_data/new_run/mltp_smpl/fastq/KA1k_R1_001.fastq
  test_data/new_run/mltp_smpl/fastq/KA1k_R2_001.fastq
  test_data/new_run/mltp_smpl/fastq/QA1k_R1_001.fastq
  test_data/new_run/mltp_smpl/fastq/QA1k_R2_001.fastq
  test_data/new_run/mltp_smpl/results/files_list
  test_data/new_run/mltp_smpl/script/travis_job.sh
  test_data/new_run/single_smpl/fastq/F3D0_S188_L001_R1_001.fastq
  test_data/new_run/single_smpl/fastq/F3D0_S188_L001_R2_001.fastq
  test_data/new_run/single_smpl/fastq/KA1k_R1_001.fastq
  test_data/new_run/single_smpl/fastq/KA1k_R2_001.fastq
  test_data/new_run/single_smpl/results/files_list
  test_data/new_run/single_smpl/script/travis_job.sh
  test_data/samples/KA1k_R1_001.fastq
  test_data/samples/KA1k_R2_001.fastq
  test_data/samples/QA1k_R1_001.fastq
  test_data/samples/QA1k_R2_001.fastq
Labels: enhancement

#126 UPD#125
  templates/analysis_template.sh.j2
  test_data/analysis/mltp_smpl/script/analysis_travis_job.sh
  test_data/analysis/single_smpl/script/analysis_travis_job.sh
Labels: update

#127 Enh#102
  .travis.yml
  mothulity/mothulity
  setup.py
  templates/preproc_template.sh.j2
  test_data/analysis/mltp_smpl/script/analysis_travis_job.sh
  test_data/analysis/mltp_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.0.03.cons.tax.summary
  test_data/analysis/mltp_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.0.03.pick.0.03.cons.tax.summary
  test_data/analysis/mltp_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.0.03.pick.shared
  test_data/analysis/mltp_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.shared
  test_data/analysis/single_smpl/script/analysis_travis_job.sh
  test_data/analysis/single_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.0.03.cons.tax.summary
  test_data/analysis/single_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.0.03.pick.0.03.cons.tax.summary
  test_data/analysis/single_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.0.03.pick.shared
  test_data/analysis/single_smpl/shared_tax/travis_job.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.agc.unique_list.shared
  test_data/new_run/mltp_smpl/results/files_list
  test_data/new_run/mltp_smpl/script/travis_job.sh
  test_data/new_run/single_smpl/results/files_list
  test_data/new_run/single_smpl/script/travis_job.sh
Labels: enhancement

#133 Bug#132
  mothulity/utilities.py
  test_data/utilities/ref_daughter_df.csv
  tests/tests.py
Labels: bug

#131 Enh#130
  .travis.yml
  mothulity/mothulity
  mothulity/utilities.py
  templates/preproc_template.sh.j2
  test_data/database/t19_v3v4.align
  test_data/logs/cut_db_fail.log
  test_data/logs/cut_db_v3v4.log
Labels: enhancement
